In [2]:
import pandas as pd

In [2]:
# Read the CSV file
df = pd.read_csv('/emails/prospects-email.csv',
                 skiprows=1,  # Skip the title row
                 usecols=[1,2,3,4],  # Only use columns with actual data
                 names=['COMPANY_NAME', 'DESIGNATION', 'PHONE_NUMBER', 'EMAIL'],  # Define column names
                 na_values=[''])  # Convert empty strings to NaN

# Clean the data
df = df.dropna(subset=['EMAIL']) 
df = df.reset_index(drop=True) 

print("First few rows of the dataframe:")
print(df.head().to_markdown())
print("\nDataframe info:")
print(df.info())

First few rows of the dataframe:
|    | COMPANY_NAME    | DESIGNATION                   | PHONE_NUMBER    | EMAIL                       |
|---:|:----------------|:------------------------------|:----------------|:----------------------------|
|  0 | COMPANY NAME    | DESIGNATION                   | PHONE NUMBER    | EMAIL ADRESS                |
|  1 | Bidco Africa    | regional sales head           | +254 67 2821000 | saurabh.suman@bidco-oil.com |
|  2 | CCBA kenya      | country lead-Jennifer mbindyo | (011) 848-2600  | jmbindyo@ccbagroup.com      |
|  3 | CIC Group       | General manager sales         | +254 703 099120 | njerenga@cic.co.ke          |
|  4 | BRITAM HOLDINGS | CHAIRMAN                      | nan             | kmuchiru@britam.com         |

Dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   COMPANY_NAME  89 non-null     object
 1   DESIGNATION   118 non-null    object
 2   PHONE_NUMBER  86 non-null     object
 3   EMAIL         128 non-null    object
dtypes: object(4)
memory usage: 4.1+ KB
None

In [3]:
df = df.iloc[1:].reset_index(drop=True)
df.head()

,COMPANY_NAME,DESIGNATION,PHONE_NUMBER,EMAIL
0,Bidco Africa,regional sales head,+254 67 2821000,saurabh.suman@bidco-oil.com
1,CCBA kenya,country lead-Jennifer mbindyo,(011) 848-2600,jmbindyo@ccbagroup.com
2,CIC Group,General manager sales,+254 703 099120,njerenga@cic.co.ke
3,BRITAM HOLDINGS,CHAIRMAN,NaN,kmuchiru@britam.com
4,LIBERTY INSURANCE,head of customer experience,+254 711 028000,angela.rarieya@libertylife.co.ke

In [4]:
df_prospects_email = df[["EMAIL"]]
df_prospects_email.head()

                              EMAIL
0       saurabh.suman@bidco-oil.com
1            jmbindyo@ccbagroup.com
2                njerenga@cic.co.ke
3               kmuchiru@britam.com
4  angela.rarieya@libertylife.co.ke

In [5]:
df_prospects_email.isna().sum()

EMAIL    0
dtype: int64

In [6]:
df_prospects_email.loc[:, "EMAIL"] = df_prospects_email["EMAIL"].str.strip().str.lower()
df_prospects_email.head()

                              EMAIL
0       saurabh.suman@bidco-oil.com
1            jmbindyo@ccbagroup.com
2                njerenga@cic.co.ke
3               kmuchiru@britam.com
4  angela.rarieya@libertylife.co.ke

In [7]:
df_prospects_email = df_prospects_email.rename(columns={"EMAIL": "Emails"})
df_prospects_email.columns

Index(['Emails'], dtype='object')

In [8]:
df_prospects_email.duplicated().sum()

np.int64(0)

In [9]:
df_prospects_email["cc"] = "info@ascent-institute.com"
df_prospects_email.head()

                             Emails                         cc
0       saurabh.suman@bidco-oil.com  info@ascent-institute.com
1            jmbindyo@ccbagroup.com  info@ascent-institute.com
2                njerenga@cic.co.ke  info@ascent-institute.com
3               kmuchiru@britam.com  info@ascent-institute.com
4  angela.rarieya@libertylife.co.ke  info@ascent-institute.com

In [10]:
df_prospects_email.shape

(127, 2)

In [11]:
df_prospects_email.to_csv('prospects-email-cleaned.csv', index=False)

In [12]:
df_governance = pd.read_csv("emails/old/governance-emails.csv")
df_governance["cc"] = "info@ascent-institute.com"
df_governance.head()

                              EMAILS                          cc
0                     info@cargen.com  info@ascent-institute.com
1  elizabeth@charteredengineering.com  info@ascent-institute.com
2             info@firstlenders.co.ke  info@ascent-institute.com
3            amina@blackwoodhodge.com  info@ascent-institute.com
4             sales@hydromaticsea.com  info@ascent-institute.com

In [13]:
df_governance = df_governance.rename(columns={"EMAILS": "Emails"})
display(df_governance.head())

                              EMAILS                          cc
0                     info@cargen.com  info@ascent-institute.com
1  elizabeth@charteredengineering.com  info@ascent-institute.com
2             info@firstlenders.co.ke  info@ascent-institute.com
3            amina@blackwoodhodge.com  info@ascent-institute.com
4             sales@hydromaticsea.com  info@ascent-institute.com

In [14]:
df_governance.to_csv('governance-email-cleaned.csv', index=False)

# New emails

In [15]:
df_emails_new = pd.read_csv("emails/old/emails-new.csv")
df_emails_new["cc"] = "info@ascent-institute.com"
print(df_emails_new.columns)
print(df_emails_new.head().to_markdown())

Index(['Emails', 'cc'], dtype='object')
|    | Emails                   | cc                        |
|---:|:-------------------------|:--------------------------|
|  0 | swakiomaghanga@gmail.com | info@ascent-institute.com |
|  1 | nyonesaj12@yahoo.com     | info@ascent-institute.com |
|  2 | paulsimiyu74@gmail.com   | info@ascent-institute.com |
|  3 | mutiemota@gmail.com      | info@ascent-institute.com |
|  4 | velentiah80@yahoo.com    | info@ascent-institute.com |

In [16]:
df_prospects_email = pd.read_csv("emails/old/prospects-email-super-cleaned.csv")
df_governance_email = pd.read_csv("emails/old/governance-email-super-cleaned.csv")
print(df_emails_new.columns)
print(df_prospects_email.columns)
print(df_governance.columns)

Index(['Emails', 'cc'], dtype='object')
Index(['Emails', 'cc'], dtype='object')
Index(['EMAILS ', 'cc'], dtype='object')

In [17]:
print("Expected length after concating all should be: ", len(df_emails_new) + len(df_prospects_email) + len(df_governance_email))

Expected length after concating all should be:  220

In [18]:
df_combined = pd.concat([
    df_emails_new[['Emails']], 
    df_prospects_email[['Emails']], 
    df_governance[['EMAILS ']]
], axis=0)
display(df_combined.shape)
print(df_combined.head().to_markdown())

(349, 2)

|    | Emails                   |   EMAILS  |
|---:|:-------------------------|----------:|
|  0 | swakiomaghanga@gmail.com |       nan |
|  1 | nyonesaj12@yahoo.com     |       nan |
|  2 | paulsimiyu74@gmail.com   |       nan |
|  3 | mutiemota@gmail.com      |       nan |
|  4 | velentiah80@yahoo.com    |       nan |

In [19]:
df_combined.dropna(subset=["Emails"], inplace=True)
df_combined["cc"] = "info@ascent-institute.com"
df_combined.head()

                     Emails EMAILS                          cc
0  swakiomaghanga@gmail.com     NaN  info@ascent-institute.com
1      nyonesaj12@yahoo.com     NaN  info@ascent-institute.com
2    paulsimiyu74@gmail.com     NaN  info@ascent-institute.com
3       mutiemota@gmail.com     NaN  info@ascent-institute.com
4     velentiah80@yahoo.com     NaN  info@ascent-institute.com

In [20]:
df_combined["cc"] = "info@ascent-institute.com"
# df_combined.dropna(subset=["EMAILS "], inplace=True)
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 74
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Emails   164 non-null    object
 1   EMAILS   0 non-null      object
 2   cc       164 non-null    object
dtypes: object(3)
memory usage: 5.1+ KB

In [21]:
df_combined.drop_duplicates(subset=["Emails"], inplace=True)
df_combined.tail()

,Emails,EMAILS,cc
70,miriam@scopeandimpact.com,NaN,info@ascent-institute.com
71,jkarasha@sanlam.co.ke,NaN,info@ascent-institute.com
72,james.waweru@apainsurance.org,NaN,info@ascent-institute.com
73,manan.desai@apainsurance.org,NaN,info@ascent-institute.com
74,"info@dimkessacco.co.ke , hr@dimkessacco.co.ke",NaN,info@ascent-institute.com

In [22]:
# df_combined = df_combined.drop(columns=["EMAILS "])
df_combined["Emails"] = df_combined["Emails"].str.strip().str.lower()
df_combined.columns

Index(['Emails', 'EMAILS ', 'cc'], dtype='object')

# March 18

In [24]:
# Dropping emails that do are persistent yet they dont exist
main_combined_emails = pd.read_csv("emails/old/main-combined.csv")
email_to_drop = ["benard.mutua@royalmedia.co.ke", "info@dtdobie.co.ke", "imelda@kibandatopup.com", "ruth.mwende@agritechsolutions.com", "margaret.njeri@blueskyinvestments.com", "mary.smith@xyzfinance.com", "dennis.kaai@outloook.com", "linda.brown@globalsolutions.com","dmshigati@yahoo.com", "chrispongah@gmail.com", "lucy.wambui@agrifuture.com", "pisu18@singnet.com.sg", "mary.wambui@techleaders.com", "grace.mumbi@ecofinance.com", "velentiah80@yahoo.com", "somoile.j@gmail.com", "m4anyambura@yahoo.com", "pmwamkey@gmail.com", "dianemwashoma@gmail.com", "mercyshikosh@gmail.com", "ramahkatho@gmail.com", "beahcelekcdcc@gmail.com", "beahcelekcdcc@gmail.com", "bethuel.mwangi@airtelkenya.com", "enock@kapa-oil.com", "sahcadmin@africaonline.co.ke", "cpsb@kiambu.go.ke", "susan.johnson@techinnovators.com", "grace.nyambura@cleanwatersolutions.com", "margaret.mwangi@healthplus.com", "nancy.wairimu@futureleaders.com", "lucy.wanjiku@builditconstruction.com", "mary.wanjiru@techinnovate.com", "joyce.akinyi@greenenergy.com", "elizabeth.wanjiku@inclusivegrowth.com", "wanjiku@safefinance.com", "elizabeth.njeri@inclusivefutures.com"]
email_to_drop_cleaned = [email.lower().strip() for email in email_to_drop]
print("Before dropping Invalid emails size is: ", len(main_combined_emails))
df_combined = main_combined_emails[~main_combined_emails["Emails"].isin(email_to_drop_cleaned)].copy()
print("After dropping Invalid emails size is: ", len(df_combined))

print("*" * 10)
print("Before dropping duplicates the size is: ", len(df_combined))
df_combined.drop_duplicates(inplace=True)
print("After dropping duplicates the size is: ", len(df_combined))

Before dropping Invalid emails size is:  163
After dropping Invalid emails size is:  147
**********
Before dropping duplicates the size is:  147
After dropping duplicates the size is:  147

In [25]:
failed_emails_df = pd.DataFrame(email_to_drop_cleaned, columns=["Emails"])
cleaned_emails_df = df_combined["Emails"].copy()
cleaned_emails_df = pd.DataFrame(cleaned_emails_df, columns=["Emails"])  # Convert to DataFrame
cleaned_emails_df["cc"] = "info@ascent-institute.com"  # Add 'cc' column
display(cleaned_emails_df)  # Display the DataFrame

                                            Emails                         cc
0                         swakiomaghanga@gmail.com  info@ascent-institute.com
1                             nyonesaj12@yahoo.com  info@ascent-institute.com
2                           paulsimiyu74@gmail.com  info@ascent-institute.com
3                              mutiemota@gmail.com  info@ascent-institute.com
7                                 nwmash@gmail.com  info@ascent-institute.com
..                                             ...                        ...
158                      miriam@scopeandimpact.com  info@ascent-institute.com
159                          jkarasha@sanlam.co.ke  info@ascent-institute.com
160                  james.waweru@apainsurance.org  info@ascent-institute.com
161                   manan.desai@apainsurance.org  info@ascent-institute.com
162  info@dimkessacco.co.ke , hr@dimkessacco.co.ke  info@ascent-institute.com

[147 rows x 2 columns]

In [26]:
failed_emails_df.head()

                                  Emails
0          benard.mutua@royalmedia.co.ke
1                     info@dtdobie.co.ke
2                imelda@kibandatopup.com
3      ruth.mwende@agritechsolutions.com
4  margaret.njeri@blueskyinvestments.com

In [27]:
cleaned_emails_df.head()

                     Emails                         cc
0  swakiomaghanga@gmail.com  info@ascent-institute.com
1      nyonesaj12@yahoo.com  info@ascent-institute.com
2    paulsimiyu74@gmail.com  info@ascent-institute.com
3       mutiemota@gmail.com  info@ascent-institute.com
7          nwmash@gmail.com  info@ascent-institute.com

In [28]:
failed_emails_df.to_excel("failed-emails.xlsx", index=False)
cleaned_emails_df[["Emails"]].to_excel("valid-emails.xlsx", index=False)

In [29]:
print("Total failed emails: ", len(failed_emails_df))
print("Total valid emails: ", len(cleaned_emails_df))

Total failed emails:  37
Total valid emails:  147

In [30]:
# Adding the `cc` column before exporting
cleaned_emails_df.to_csv('combined-emails-cleaned.csv', index=False)

In [31]:
cleaned_emails_df

                                            Emails                         cc
0                         swakiomaghanga@gmail.com  info@ascent-institute.com
1                             nyonesaj12@yahoo.com  info@ascent-institute.com
2                           paulsimiyu74@gmail.com  info@ascent-institute.com
3                              mutiemota@gmail.com  info@ascent-institute.com
7                                 nwmash@gmail.com  info@ascent-institute.com
..                                             ...                        ...
158                      miriam@scopeandimpact.com  info@ascent-institute.com
159                          jkarasha@sanlam.co.ke  info@ascent-institute.com
160                  james.waweru@apainsurance.org  info@ascent-institute.com
161                   manan.desai@apainsurance.org  info@ascent-institute.com
162  info@dimkessacco.co.ke , hr@dimkessacco.co.ke  info@ascent-institute.com

[147 rows x 2 columns]

# March 20

In [3]:
df_march_20 = pd.read_csv("emails/march-20/Governance-21st-century-to-send.csv")
df_march_20.head()

                         Emails
0             info@quipbank.com
1  info@ruraldistributors.co.ke
2    info@unitedsmeskenya.or.ke
3       info@lisamuventures.com
4    info@eddietenkventures.com

In [6]:
df_march_20["cc"] = "info@ascent-institute.com"
print("Before dropping duplicates: ", len(df_march_20))
df_march_20.drop_duplicates(subset=["Emails"], inplace=True)
print("After dropping duplicates: ", len(df_march_20))
df_march_20.head()

Before dropping duplicates:  213
After dropping duplicates:  213

                         Emails                         cc
0             info@quipbank.com  info@ascent-institute.com
1  info@ruraldistributors.co.ke  info@ascent-institute.com
2    info@unitedsmeskenya.or.ke  info@ascent-institute.com
3       info@lisamuventures.com  info@ascent-institute.com
4    info@eddietenkventures.com  info@ascent-institute.com

In [18]:
df_march_20.to_csv('Governance-21st-century-to-send-cleaned.csv', index=False)

In [5]:
df_march_20_pension_advanced_records_reminder = pd.read_csv("emails/march-20/pension-advanced-records-reminder-to-send.csv")
df_march_20_pension_advanced_records_reminder.head()

                      Emails
0             info@ict.go.ke
1        info@archives.go.ke
2       callcentre@kra.go.ke
3  info@landcommission.go.ke
4         info@nairobi.go.ke

In [6]:
df_march_20_pension_advanced_records_reminder["cc"] = "info@ascent-institute.com"
print("Before dropping duplicates: ", len(df_march_20_pension_advanced_records_reminder))
df_march_20_pension_advanced_records_reminder.drop_duplicates(subset=["Emails"], inplace=True)
print("After dropping duplicates: ", len(df_march_20_pension_advanced_records_reminder))
df_march_20_pension_advanced_records_reminder.head()

Before dropping duplicates:  38
After dropping duplicates:  38

                      Emails                         cc
0             info@ict.go.ke  info@ascent-institute.com
1        info@archives.go.ke  info@ascent-institute.com
2       callcentre@kra.go.ke  info@ascent-institute.com
3  info@landcommission.go.ke  info@ascent-institute.com
4         info@nairobi.go.ke  info@ascent-institute.com

In [7]:
df_march_20_pension_advanced_records_reminder.to_csv('pension-advanced-records-reminder-to-send-cleaned.csv', index=False)